### ISSUE TITLE
Index Reference Metadata job error

### ISSUE THREAD

**Issue by adehner** [Daniel-KM/Omeka-S-module-Reference#19]
When running the Index Reference Metadata job, I'm getting the following error:

2024-02-02T02:21:09+00:00 NOTICE (5): Starting creation of reference metadata. {"referenceId":"Reference/Metadata/job_10"}
2024-02-02T02:21:10+00:00 ERR (3): Doctrine\ORM\EntityNotFoundException: Unable to find "DoctrineProxies\__CG__\Omeka\Entity\Item" entity identifier associated with the UnitOfWork in /home/annelies/public_html/plpr4/vendor/doctrine/orm/lib/Doctrine/ORM/EntityNotFoundException.php:43
Stack trace:
#0 /home/annelies/public_html/plpr4/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(3082): Doctrine\ORM\EntityNotFoundException::noIdentifierFound('DoctrineProxies...')
#1 /home/annelies/public_html/plpr4/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(690): Doctrine\ORM\UnitOfWork->getEntityIdentifier(Object(DoctrineProxies\__CG__\Omeka\Entity\Item))
#2 /home/annelies/public_html/plpr4/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(727): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->prepareUpdateData(Object(Reference\Entity\Metadata), true)
#3 /home/annelies/public_html/plpr4/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(266): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->prepareInsertData(Object(Reference\Entity\Metadata))
#4 /home/annelies/public_html/plpr4/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1128): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#5 /home/annelies/public_html/plpr4/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(425): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#6 /home/annelies/public_html/plpr4/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(392): Doctrine\ORM\UnitOfWork->commit(NULL)
#7 /home/annelies/public_html/plpr4/modules/Reference/src/Job/UpdateReferenceMetadata.php(103): Doctrine\ORM\EntityManager->flush()
#8 /home/annelies/public_html/plpr4/application/src/Job/DispatchStrategy/Synchronous.php(34): Reference\Job\UpdateReferenceMetadata->perform()
#9 /home/annelies/public_html/plpr4/modules/Common/src/Job/Dispatcher.php(27): Omeka\Job\DispatchStrategy\Synchronous->send(Object(Omeka\Entity\Job))
#10 /home/annelies/public_html/plpr4/application/data/scripts/perform-job.php(66): Common\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Omeka\Job\DispatchStrategy\Synchronous))
#11 {main} {"referenceId":"Reference/Metadata/job_10"}

I'm not sure if the problem is with the Reference or Advanced Search module.

Omeka 4.04
Advanced Search (3.4.20), Block Plus (3.4.20), CSV Import (2.5.1), Common (3.4.49), Custom Ontology (3.4.5.1), Data Type RDF (3.4.8), File Sideload (1.7.1), Internationalisation (3.4.13), Mapping (1.10.0), Menu (3.4.8), Numeric Data Types (1.11.3), Random Items Block (0.3.0), Reference (3.4.47)

**Comment by adehner** [comment]
The UpdateReferenceMetadata job completes successfully in 3.4.44 for both Omeka S v.4 and Omeka S v.3. Later versions fail in both Omeka 3 and 4.

**Comment by zerocrates** [comment]
I've suggested a fix here https://gitlab.com/Daniel-KM/Omeka-S-module-Reference/-/merge_requests/3

**Comment by hxsllc** [comment]
@adehner hello! And Daniel and John. My favorite Omeka people all here in one thread :) This thread became essential to our Edison Papers upgrade. The index metadata job was failing (which by the way took me a while to figure out it was even needed after an upgrade from v3 to v4 + module upgrade, it is not mentioned anywhere I can see)... exactly as Anneliese reports.

Due to a MariaDB version issue, we had to upgrade to Omeka-S v4.0.4, and therefore Reference v3.4.48 which does not have this patch.

I actually manually patched based on John's merge request, and it works! We have ~500,000 elements that need indexing according to the log messages. And if we had moved forwards with the upgrade in January as planned... this would have been a blocker forcing us to revert.

**Comment by Daniel-KM** [comment]
Fixed in the pr.
