### ISSUE TITLE
Error: Unexpected 'Omeka\Entity\Item'

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-Reference#8]
I have this error when adding a reference block (no matter which) on Omeka S 2.0.2.

Is it just because this module needs an upgrade before being usable for 2.0.2? Or is there something else to check on my side?

```

Omeka S a rencontré une erreur

Doctrine\ORM\Query\QueryException
[Syntax Error] line 0, col 284: Error: Unexpected 'Omeka\Entity\Item'

Détails :

Doctrine\ORM\Query\QueryException: SELECT COUNT(DISTINCT value.value) FROM Omeka\Entity\Value value INNER JOIN Omeka\Entity\Resource resource WITH value.resource = resource INNER JOIN Omeka\Entity\Item res WITH resource.id = res.id WHERE value.property = :property AND value.value IS NOT NULL AND resource.id IN(SELECT Omeka\Entity\Item.id FROM Omeka\Entity\Item Omeka\Entity\Item INNER JOIN omeka_root.itemSets omeka_2 WITH omeka_2.id IN(:omeka_3)) in /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:43
Stack trace:
#0 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(456): Doctrine\ORM\Query\QueryException::dqlError('SELECT COUNT(DI...')
#1 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2005): Doctrine\ORM\Query\Parser->syntaxError()
#2 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2362): Doctrine\ORM\Query\Parser->ScalarExpression()
#3 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1209): Doctrine\ORM\Query\Parser->SimpleSelectExpression()
#4 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1428): Doctrine\ORM\Query\Parser->SimpleSelectClause()
#5 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(3087): Doctrine\ORM\Query\Parser->Subselect()
#6 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2572): Doctrine\ORM\Query\Parser->InExpression()
#7 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2474): Doctrine\ORM\Query\Parser->SimpleConditionalExpression()
#8 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2450): Doctrine\ORM\Query\Parser->ConditionalPrimary()
#9 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2423): Doctrine\ORM\Query\Parser->ConditionalFactor()
#10 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2393): Doctrine\ORM\Query\Parser->ConditionalTerm()
#11 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1360): Doctrine\ORM\Query\Parser->ConditionalExpression()
#12 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(880): Doctrine\ORM\Query\Parser->WhereClause()
#13 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(847): Doctrine\ORM\Query\Parser->SelectStatement()
#14 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(260): Doctrine\ORM\Query\Parser->QueryLanguage()
#15 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(359): Doctrine\ORM\Query\Parser->getAST()
#16 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(283): Doctrine\ORM\Query\Parser->parse()
#17 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(295): Doctrine\ORM\Query->_parse()
#18 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(967): Doctrine\ORM\Query->_doExecute()
#19 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(922): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, 4)
#20 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(803): Doctrine\ORM\AbstractQuery->execute(NULL, 4)
#21 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(831): Doctrine\ORM\AbstractQuery->getSingleResult(4)
#22 /sites/erudhilor/www/web_main/modules/Reference/src/Mvc/Controller/Plugin/Reference.php(841): Doctrine\ORM\AbstractQuery->getSingleScalarResult()
#23 /sites/erudhilor/www/web_main/modules/Reference/src/Mvc/Controller/Plugin/Reference.php(293): Reference\Mvc\Controller\Plugin\Reference->countReferences(1, 'properties', 'Omeka\\Entity\\It...', Array)
#24 /sites/erudhilor/www/web_main/modules/Reference/src/Site/BlockLayout/Reference.php(121): Reference\Mvc\Controller\Plugin\Reference->count('dcterms:title', 'properties', 'items', Array)
#25 /sites/erudhilor/www/web_main/application/src/View/Helper/BlockLayout.php(124): Reference\Site\BlockLayout\Reference->render(Object(Zend\View\Renderer\PhpRenderer), Object(Omeka\Api\Representation\SitePageBlockRepresentation))
#26 /sites/erudhilor/www/web_main/application/view/omeka/site/page/content.phtml(9): Omeka\View\Helper\BlockLayout->render(Object(Omeka\Api\Representation\SitePageBlockRepresentation))
#27 /sites/erudhilor/www/web_main/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(506): include('/sites/erudhilo...')
#28 /sites/erudhilor/www/web_main/vendor/zendframework/zend-view/src/View.php(207): Zend\View\Renderer\PhpRenderer->render(NULL)
#29 /sites/erudhilor/www/web_main/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#30 /sites/erudhilor/www/web_main/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#31 /sites/erudhilor/www/web_main/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#32 /sites/erudhilor/www/web_main/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#33 /sites/erudhilor/www/web_main/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(105): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#34 /sites/erudhilor/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#35 /sites/erudhilor/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent))
#36 /sites/erudhilor/www/web_main/vendor/zendframework/zend-mvc/src/Application.php(367): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#37 /sites/erudhilor/www/web_main/vendor/zendframework/zend-mvc/src/Application.php(348): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#38 /sites/erudhilor/www/web_main/index.php(21): Zend\Mvc\Application->run()
#39 {main}

Next Doctrine\ORM\Query\QueryException: [Syntax Error] line 0, col 284: Error: Unexpected 'Omeka\Entity\Item' in /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:54
Stack trace:
#0 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(456): Doctrine\ORM\Query\QueryException::syntaxError('line 0, col 284...', Object(Doctrine\ORM\Query\QueryException))
#1 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2005): Doctrine\ORM\Query\Parser->syntaxError()
#2 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2362): Doctrine\ORM\Query\Parser->ScalarExpression()
#3 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1209): Doctrine\ORM\Query\Parser->SimpleSelectExpression()
#4 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1428): Doctrine\ORM\Query\Parser->SimpleSelectClause()
#5 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(3087): Doctrine\ORM\Query\Parser->Subselect()
#6 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2572): Doctrine\ORM\Query\Parser->InExpression()
#7 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2474): Doctrine\ORM\Query\Parser->SimpleConditionalExpression()
#8 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2450): Doctrine\ORM\Query\Parser->ConditionalPrimary()
#9 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2423): Doctrine\ORM\Query\Parser->ConditionalFactor()
#10 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2393): Doctrine\ORM\Query\Parser->ConditionalTerm()
#11 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1360): Doctrine\ORM\Query\Parser->ConditionalExpression()
#12 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(880): Doctrine\ORM\Query\Parser->WhereClause()
#13 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(847): Doctrine\ORM\Query\Parser->SelectStatement()
#14 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(260): Doctrine\ORM\Query\Parser->QueryLanguage()
#15 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(359): Doctrine\ORM\Query\Parser->getAST()
#16 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(283): Doctrine\ORM\Query\Parser->parse()
#17 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(295): Doctrine\ORM\Query->_parse()
#18 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(967): Doctrine\ORM\Query->_doExecute()
#19 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(922): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, 4)
#20 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(803): Doctrine\ORM\AbstractQuery->execute(NULL, 4)
#21 /sites/erudhilor/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(831): Doctrine\ORM\AbstractQuery->getSingleResult(4)
#22 /sites/erudhilor/www/web_main/modules/Reference/src/Mvc/Controller/Plugin/Reference.php(841): Doctrine\ORM\AbstractQuery->getSingleScalarResult()
#23 /sites/erudhilor/www/web_main/modules/Reference/src/Mvc/Controller/Plugin/Reference.php(293): Reference\Mvc\Controller\Plugin\Reference->countReferences(1, 'properties', 'Omeka\\Entity\\It...', Array)
#24 /sites/erudhilor/www/web_main/modules/Reference/src/Site/BlockLayout/Reference.php(121): Reference\Mvc\Controller\Plugin\Reference->count('dcterms:title', 'properties', 'items', Array)
#25 /sites/erudhilor/www/web_main/application/src/View/Helper/BlockLayout.php(124): Reference\Site\BlockLayout\Reference->render(Object(Zend\View\Renderer\PhpRenderer), Object(Omeka\Api\Representation\SitePageBlockRepresentation))
#26 /sites/erudhilor/www/web_main/application/view/omeka/site/page/content.phtml(9): Omeka\View\Helper\BlockLayout->render(Object(Omeka\Api\Representation\SitePageBlockRepresentation))
#27 /sites/erudhilor/www/web_main/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(506): include('/sites/erudhilo...')
#28 /sites/erudhilor/www/web_main/vendor/zendframework/zend-view/src/View.php(207): Zend\View\Renderer\PhpRenderer->render(NULL)
#29 /sites/erudhilor/www/web_main/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#30 /sites/erudhilor/www/web_main/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#31 /sites/erudhilor/www/web_main/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#32 /sites/erudhilor/www/web_main/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#33 /sites/erudhilor/www/web_main/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(105): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#34 /sites/erudhilor/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#35 /sites/erudhilor/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent))
#36 /sites/erudhilor/www/web_main/vendor/zendframework/zend-mvc/src/Application.php(367): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#37 /sites/erudhilor/www/web_main/vendor/zendframework/zend-mvc/src/Application.php(348): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#38 /sites/erudhilor/www/web_main/index.php(21): Zend\Mvc\Application->run()
#39 {main}


```

**Comment by Daniel-KM** [comment]
yes, the module is not yet compatible with Omeka 2.

**Comment by Daniel-KM** [comment]
The module has been released for Omeka 2.
